# Keta ML config file
log:
  level: "INFO"
  dir_name: "./log"
  file_name: "keta_ml.log"
  max_bytes: "209715200"
  backup_count: "5"
flight:
  host: "0.0.0.0"
  port: 5005
mysql:
  host: mysql-svc
  port: "3306"
  user: root
  password: ketaops1234
  database: phoenix
  pool_size: 16
algo:
  max_fit_size: 1000000
  max_apply_size: 1000000
model:
  # set global max_allowed_packet: "100*1024*1024"
  max_model_size: 104857600
  list_models_batch_size: 1024
