{{- if .Values.enabled }}
{{- $namespace := .Release.Namespace -}}
{{- if .Values.kubernetesMetric.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $namespace }}_{{ .Release.Name }}:view
rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    - persistentvolumeclaims
    - nodes
    - nodes/stats
    - endpoints
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - pods
    - configmaps
    - namespaces
    - events
    - serviceaccounts
    - resourcequotas
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - replicasets
    - ingresses/status
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - statefulsets
    - deployments
    - replicasets
    - daemonsets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    - clusterroles
    - rolebindings
    - roles
    verbs:
    - list
    - watch
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - list
    - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ketad.serviceAccountName" . }}
  labels:
    {{- include "ketad.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $namespace }}_{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "ketad.serviceAccountName" . }} # 指定用户名
roleRef:
  kind: ClusterRole
  name: {{ $namespace }}_{{ .Release.Name }}:view # 角色名
  apiGroup: "rbac.authorization.k8s.io" # ""表示角色在核心API组中
{{- end }}
{{- end }}