---
{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "ketadb.uname" . }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4}}
{{- end }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: {{ template "ketadb.uname" . }}
  ports:
  {{- range $key,$value := .Values.service.ports }}
  - name: {{ $key }}
    protocol: TCP
    port: {{ $value }}
  {{- end }}

{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.service.extraPorts }}
{{ toYaml .Values.service.extraPorts | indent 2}}
{{- end }}
{{- end }}

---
{{- if .Values.roles.master }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "ketadb.uname" . }}-headless
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "ketadb.uname" . }}"
{{- if .Values.service.labelsHeadless }}
{{ toYaml .Values.service.labelsHeadless | indent 4 }}
{{- end }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like ketadb-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: "{{ template "ketadb.uname" . }}"
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
  - name: transport
    port: {{ .Values.service.ports.transport }}
{{- end }}