

clusterName: "ketadb"
replicas: 3

roles:
  master: true
  web: true
  data: true
  ingest: true

podManagementPolicy: OrderedReady  # 并发部署
updateStrategy: RollingUpdate  # 滚动升级

image: 
  repository: "docker.ketaops.cc/ketaops/ketadb"
  tag: "v1.2.2"
  PullPolicy: "Always"

pod:
  labels: {}  # 为pod添加标签
  annotations: {}  # 为pod添加注释

KETA_JAVA_OPTS: "" # default: "-Xmx2g -Xms2g"

service:
  labels: {}
  type: ClusterIP
  nodePort: ""
  annotations: {}
  ports:
    http: "9200"
    transport: "9300"
    monitor: "10005"
    heartbeat: "9400"
    rpc: "9500"
    debug: "9600"
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  extraPorts: []

resources:
  requests:
    cpu: "2000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

persistence:
  enabled: true
  annotations: {}

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  # storageClassName: ""
  resources:
    requests:
      storage: 30Gi

podSecurityContext:
  fsGroup: 0
  runAsUser: 0

securityContext:
  privileged: true #  Processes in privileged containers are essentially equivalent to root on the host.
  capabilities: 
    drop: []
    add:
      - SYS_ADMIN
      - NET_RAW
      - NET_ADMIN
  # readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 0

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: /
  hostsSuffix:
    - example.com
  tls: 
    # - hosts:
    #   - example.com
    #   secretName: testserect-tls
    
nodeSelector: {}
tolerations: []
# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "hard"
nodeAffinity: {}
antiAffinityTopologyKey: "kubernetes.io/hostname"

# This is the PriorityClass settings as defined in
# https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: ""

# How long to wait for ketadb to stop gracefully
terminationGracePeriod: 30

sysctlInitContainer:
  enabled: true
  sysctlVmMaxMapCount: 262144
  resources: {}

extraInitContainers: []

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 10

livenessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10

dcServerUrl: ""
dcServerHeartbeats: ""
dcDataTransUrls: ""
alertHost: ""

licenseCheckInterval: "300"

unicast: ""


env: {}
  

envFrom: [] 
# - secretRef:
#     name: env-secret
# - configMapRef:
#     name: config-map

secretMounts: []
#  - name: elastic-certificates
#    secretName: elastic-certificates
#    path: /usr/share/ketadb/config/certs

extraVolumeMounts: []
# - name: extras
#   mountPath: /usr/share/extras
#   readOnly: true

extraContainers: []
# - name: do-something
#   image: busybox
#   command: ['do', 'something']

mysql:
  # Default values for mysql.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1

  image:
    repository: "mysql"
    pullPolicy: "Always"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "8.0.32"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: "mysql"

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: NodePort
    port: 3306


  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi


  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraVolumes:
    name: mysql-data
    persistentVolumeClaimName: mysql-data-pvc
    size: 10Gi
    # storageClass: ""

  # Custom mysql configuration files path
  configurationFilesPath: /etc/mysql/conf.d/

  # Custom mysql configuration files used to override default mysql settings
  configurationFiles:
    mysql.cnf: |-
      [mysqld]
      max_connections=2000
      max-allowed-packet=1024000000
      skip_log_bin
